# PhantomLimiter Configuration

# Controls what percentage of phantom spawns are allowed to succeed. (0.0 to 1.0)
phantom-spawn-rate: 0.25

# Examples:
# Set to 0.1 for very few phantoms (10% spawn rate)
# Set to 0.0 for no phantoms at all
# Set to 1.0 for normal phantom spawning (vanilla behavior)