name: PhantomLimiter
version: '1.1'
main: org.karlssonsmp.phantomLimiter.PhantomLimiter
api-version: '1.18'
folia-supported: true

commands:
  phantomlimiter:
    description: Reload PhantomLimiter configuration
    usage: /phantomlimiter reload

permissions:
  phantomlimiter.reload:
    description: Allows reloading the plugin configuration
    default: op