name: PhantomReducer
version: '1.2'
main: org.karlssonsmp.phantomReducer.PhantomReducer
api-version: '1.18'
folia-supported: true

commands:
  phantomreducer:
    description: Reload PhantomReducer configuration
    usage: /phantomreducer reload

permissions:
  phantomreducer.reload:
    description: Allows reloading the plugin configuration
    default: op